name:                dotf-hs
version:             0.2.0.0
github:              "abjoru/dotf-hs"
license:             BSD-3-Clause
author:              "Andreas Bjoru"
maintainer:          "andreas.bjoru@gmail.com"
copyright:           "2024 Andreas Bjoru"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/abjoru/dotf-hs#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- typed-process
- directory
- filepath
- string-interpolate
- process
- brick
- vty
- unordered-containers
- text
- yaml
- aeson
- os-release
- microlens
- microlens-mtl
- microlens-th
- mtl
- vector
- text-zipper

default-extensions:
- OverloadedStrings
- TemplateHaskell
- QuasiQuotes

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  dotf-hs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dotf-hs

tests:
  dotf-hs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dotf-hs
